from enum import Enum

class VictorState(Enum):
    CLOSED = "CLOSED"
    LOCKED = "LOCKED"
    AUTHENTICATING = "AUTHENTICATING"
    AUTH_SUCCESS = "AUTH_SUCCESS"
    BIOMETRIC_PENDING = "BIOMETRIC_PENDING"
    AUTHENTICATED = "AUTHENTICATED"
    CONNECTING = "CONNECTING"
    ACTIVE = "ACTIVE"
    IDLE = "IDLE"
    LISTENING = "LISTENING"
    THINKING = "THINKING"
    EXECUTING = "EXECUTING"
    SPEAKING = "SPEAKING"
    LOCKING = "LOCKING"
    ERROR = "ERROR"
    OFFLINE = "OFFLINE"