"""
Domain models for Victor's Coding Computer Control module.

Defines schemas for project metadata, compact AI context, coding plans,
file modifications, command execution results, and persistent workspace state.
"""

from __future__ import annotations

import time
from enum import Enum
from typing import Any
from pydantic import BaseModel, Field


class ProjectType(str, Enum):
    PYTHON = "python"
    NODE = "node"
    CSHARP = "csharp"
    RUST = "rust"
    GO = "go"
    JAVA = "java"
    UNKNOWN = "unknown"


class ProjectMetadata(BaseModel):
    """Detected language, framework, build tools, and configuration."""
    project_type: ProjectType = ProjectType.UNKNOWN
    language: str = "unknown"
    framework: str | None = None
    config_files: list[str] = Field(default_factory=list)
    entry_points: list[str] = Field(default_factory=list)
    package_manager: str | None = None
    test_runner: str | None = None
    dependencies: list[str] = Field(default_factory=list)


class CompactProjectContext(BaseModel):
    """Compact context sent to the coding model to avoid sending entire codebases."""
    root_path: str
    project_name: str
    metadata: ProjectMetadata
    skeleton_tree: str
    key_file_summaries: dict[str, str] = Field(default_factory=dict)
    relevant_files: list[dict[str, str]] = Field(default_factory=list)


class FileActionType(str, Enum):
    CREATE_FILE = "create_file"
    MODIFY_FILE = "modify_file"
    CREATE_DIRECTORY = "create_directory"
    DELETE_FILE = "delete_file"


class FileAction(BaseModel):
    """A deterministic filesystem modification planned by the coding model."""
    path: str  # Relative to workspace root or normalized absolute
    action_type: FileActionType
    content: str = ""
    reason: str = ""


class CodingPlan(BaseModel):
    """Structured coding plan generated by the model adapter."""
    task_summary: str
    actions: list[FileAction] = Field(default_factory=list)
    run_command: str | None = None
    expected_outcome: str = ""
    notes: str = ""


class ExecutionResult(BaseModel):
    """Captured output and status from controlled terminal command execution."""
    command: str
    exit_code: int
    stdout: str
    stderr: str
    duration_seconds: float
    success: bool
    error_type: str | None = None


class CodingFixPlan(BaseModel):
    """Targeted fix plan generated after execution failure."""
    error_analysis: str
    fix_summary: str
    actions: list[FileAction] = Field(default_factory=list)
    run_command: str | None = None


class WorkspaceContext(BaseModel):
    """Persistent workspace and session state maintained across interactions."""
    workspace_path: str
    project_name: str
    metadata: ProjectMetadata
    active_files: dict[str, Any] = Field(default_factory=dict)
    recent_changes: list[dict[str, Any]] = Field(default_factory=list)
    command_history: list[ExecutionResult] = Field(default_factory=list)
    last_result: ExecutionResult | None = None
    created_at: float = Field(default_factory=time.time)
    updated_at: float = Field(default_factory=time.time)

    def record_change(self, action_type: str, path: str, details: str = "") -> None:
        self.recent_changes.append({
            "action": action_type,
            "path": path,
            "details": details,
            "timestamp": time.time(),
        })
        self.updated_at = time.time()

    def record_execution(self, result: ExecutionResult) -> None:
        self.command_history.append(result)
        self.last_result = result
        self.updated_at = time.time()
